const userModal = [
  {
    userId: 1,
    firstname: "Alex",
    lastname: "Phillips",
    email: "alex@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
    friends: [4],
  },
  {
    userId: 2,
    firstname: "John",
    lastname: "Doe",
    email: "john@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
    friends: [4],
  },
  {
    userId: 3,
    firstname: "Thomas",
    lastname: "Snow",
    email: "thomas@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
  },
  {
    userId: 4,
    firstname: "Allison",
    lastname: "Jane",
    email: "allison@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
    friends: [1, 2, 5, 7, 12],
  },
  {
    userId: 5,
    firstname: "Kane",
    lastname: "Nick",
    email: "kane@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
    friends: [4],
  },
  {
    userId: 6,
    firstname: "Chris",
    lastname: "Henry",
    email: "chris@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
    friends: [],
  },
  {
    userId: 7,
    firstname: "Glen",
    lastname: "Phillips",
    email: "glen@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
    friends: [4],
  },
  {
    userId: 8,
    firstname: "Ben",
    lastname: "Stokes",
    email: "ben@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
  },
  {
    userId: 9,
    firstname: "Joe",
    lastname: "Root",
    email: "joe@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
  },
  {
    userId: 10,
    firstname: "Steven",
    lastname: "Smith",
    email: "steven@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
  },
  {
    userId: 11,
    firstname: "Jason",
    lastname: "Holder",
    email: "jason@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
  },
  {
    userId: 12,
    firstname: "Mitchel",
    lastname: "Starc",
    email: "starc@gmail.com",
    password: "$2b$10$zm8iX2YAMlumQ17ZdznFneENhg10e7mBswfL3LCBCuLZcB.2BnSFO",
    friends: [4],
  },
];
module.exports = {
  user: userModal,
};
